version: '3'
services:
    php:
        build: ./.docker
        restart: always
        volumes:
            - ./.docker/conf/php/php.ini:/etc/php7/conf.d/50-setting.ini
            - ./.docker/conf/php/php-fpm.conf:/etc/php7/php-fpm.conf
            - ./web:/application
        depends_on:
            - mysqldb
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./web:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
            - "./.docker/conf/mysql:/etc/mysql/conf.d"
